services:
  # start postgres, and ensure that data is stored to a named volume
  database:
    image: "postgres:17"
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - ./packages/database/.env.local
    volumes:
      - pg-data:/var/lib/postgresql/data/
  # start redis, and ensure that data is stored to a named volume
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - fibapp-net

volumes:
  redis-data:
    name: redis-data
  pg-data:
    name: pg-data

networks:
  fibapp-net:
    external: true
